/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ArchitectureIndexRouteImport } from './routes/architecture.index'
import { Route as ArchitectureAgentsRouteImport } from './routes/architecture.agents'
import { Route as ArchitectureDeploymentRouteImport } from './routes/architecture.deployment'
import { Route as ArchitectureSecurityRouteImport } from './routes/architecture.security'
import { Route as MeetingsIndexRouteImport } from './routes/meetings.index'
import { Route as MeetingsIdRouteImport } from './routes/meetings.$id'
import { Route as MeetingsNewRouteImport } from './routes/meetings.new'
import { Route as MonitoringIndexRouteImport } from './routes/monitoring.index'
import { Route as MonitoringTracesIndexRouteImport } from './routes/monitoring.traces.index'
import { Route as MonitoringTracesTraceIdRouteImport } from './routes/monitoring.traces.$traceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureIndexRoute = ArchitectureIndexRouteImport.update({
  id: '/architecture/',
  path: '/architecture/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureAgentsRoute = ArchitectureAgentsRouteImport.update({
  id: '/architecture/agents',
  path: '/architecture/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureDeploymentRoute = ArchitectureDeploymentRouteImport.update({
  id: '/architecture/deployment',
  path: '/architecture/deployment',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureSecurityRoute = ArchitectureSecurityRouteImport.update({
  id: '/architecture/security',
  path: '/architecture/security',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsIndexRoute = MeetingsIndexRouteImport.update({
  id: '/meetings/',
  path: '/meetings/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsIdRoute = MeetingsIdRouteImport.update({
  id: '/meetings/$id',
  path: '/meetings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsNewRoute = MeetingsNewRouteImport.update({
  id: '/meetings/new',
  path: '/meetings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringIndexRoute = MonitoringIndexRouteImport.update({
  id: '/monitoring/',
  path: '/monitoring/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringTracesIndexRoute = MonitoringTracesIndexRouteImport.update({
  id: '/monitoring/traces/',
  path: '/monitoring/traces/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringTracesTraceIdRoute = MonitoringTracesTraceIdRouteImport.update({
  id: '/monitoring/traces/$traceId',
  path: '/monitoring/traces/$traceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/tasks': typeof TasksRoute
  '/architecture/agents': typeof ArchitectureAgentsRoute
  '/architecture/deployment': typeof ArchitectureDeploymentRoute
  '/architecture/security': typeof ArchitectureSecurityRoute
  '/meetings/$id': typeof MeetingsIdRoute
  '/meetings/new': typeof MeetingsNewRoute
  '/architecture/': typeof ArchitectureIndexRoute
  '/meetings/': typeof MeetingsIndexRoute
  '/monitoring/': typeof MonitoringIndexRoute
  '/monitoring/traces/$traceId': typeof MonitoringTracesTraceIdRoute
  '/monitoring/traces/': typeof MonitoringTracesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/tasks': typeof TasksRoute
  '/architecture/agents': typeof ArchitectureAgentsRoute
  '/architecture/deployment': typeof ArchitectureDeploymentRoute
  '/architecture/security': typeof ArchitectureSecurityRoute
  '/meetings/$id': typeof MeetingsIdRoute
  '/meetings/new': typeof MeetingsNewRoute
  '/architecture': typeof ArchitectureIndexRoute
  '/meetings': typeof MeetingsIndexRoute
  '/monitoring': typeof MonitoringIndexRoute
  '/monitoring/traces/$traceId': typeof MonitoringTracesTraceIdRoute
  '/monitoring/traces': typeof MonitoringTracesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/tasks': typeof TasksRoute
  '/architecture/agents': typeof ArchitectureAgentsRoute
  '/architecture/deployment': typeof ArchitectureDeploymentRoute
  '/architecture/security': typeof ArchitectureSecurityRoute
  '/meetings/$id': typeof MeetingsIdRoute
  '/meetings/new': typeof MeetingsNewRoute
  '/architecture/': typeof ArchitectureIndexRoute
  '/meetings/': typeof MeetingsIndexRoute
  '/monitoring/': typeof MonitoringIndexRoute
  '/monitoring/traces/$traceId': typeof MonitoringTracesTraceIdRoute
  '/monitoring/traces/': typeof MonitoringTracesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/notifications'
    | '/profile'
    | '/tasks'
    | '/architecture/agents'
    | '/architecture/deployment'
    | '/architecture/security'
    | '/meetings/$id'
    | '/meetings/new'
    | '/architecture/'
    | '/meetings/'
    | '/monitoring/'
    | '/monitoring/traces/$traceId'
    | '/monitoring/traces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/notifications'
    | '/profile'
    | '/tasks'
    | '/architecture/agents'
    | '/architecture/deployment'
    | '/architecture/security'
    | '/meetings/$id'
    | '/meetings/new'
    | '/architecture'
    | '/meetings'
    | '/monitoring'
    | '/monitoring/traces/$traceId'
    | '/monitoring/traces'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/notifications'
    | '/profile'
    | '/tasks'
    | '/architecture/agents'
    | '/architecture/deployment'
    | '/architecture/security'
    | '/meetings/$id'
    | '/meetings/new'
    | '/architecture/'
    | '/meetings/'
    | '/monitoring/'
    | '/monitoring/traces/$traceId'
    | '/monitoring/traces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  TasksRoute: typeof TasksRoute
  ArchitectureAgentsRoute: typeof ArchitectureAgentsRoute
  ArchitectureDeploymentRoute: typeof ArchitectureDeploymentRoute
  ArchitectureSecurityRoute: typeof ArchitectureSecurityRoute
  MeetingsIdRoute: typeof MeetingsIdRoute
  MeetingsNewRoute: typeof MeetingsNewRoute
  ArchitectureIndexRoute: typeof ArchitectureIndexRoute
  MeetingsIndexRoute: typeof MeetingsIndexRoute
  MonitoringIndexRoute: typeof MonitoringIndexRoute
  MonitoringTracesTraceIdRoute: typeof MonitoringTracesTraceIdRoute
  MonitoringTracesIndexRoute: typeof MonitoringTracesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture/': {
      id: '/architecture/'
      path: '/architecture'
      fullPath: '/architecture/'
      preLoaderRoute: typeof ArchitectureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture/agents': {
      id: '/architecture/agents'
      path: '/architecture/agents'
      fullPath: '/architecture/agents'
      preLoaderRoute: typeof ArchitectureAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture/deployment': {
      id: '/architecture/deployment'
      path: '/architecture/deployment'
      fullPath: '/architecture/deployment'
      preLoaderRoute: typeof ArchitectureDeploymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture/security': {
      id: '/architecture/security'
      path: '/architecture/security'
      fullPath: '/architecture/security'
      preLoaderRoute: typeof ArchitectureSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/': {
      id: '/meetings/'
      path: '/meetings'
      fullPath: '/meetings/'
      preLoaderRoute: typeof MeetingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/$id': {
      id: '/meetings/$id'
      path: '/meetings/$id'
      fullPath: '/meetings/$id'
      preLoaderRoute: typeof MeetingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/new': {
      id: '/meetings/new'
      path: '/meetings/new'
      fullPath: '/meetings/new'
      preLoaderRoute: typeof MeetingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring/': {
      id: '/monitoring/'
      path: '/monitoring'
      fullPath: '/monitoring/'
      preLoaderRoute: typeof MonitoringIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring/traces/': {
      id: '/monitoring/traces/'
      path: '/monitoring/traces'
      fullPath: '/monitoring/traces/'
      preLoaderRoute: typeof MonitoringTracesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring/traces/$traceId': {
      id: '/monitoring/traces/$traceId'
      path: '/monitoring/traces/$traceId'
      fullPath: '/monitoring/traces/$traceId'
      preLoaderRoute: typeof MonitoringTracesTraceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  TasksRoute: TasksRoute,
  ArchitectureAgentsRoute: ArchitectureAgentsRoute,
  ArchitectureDeploymentRoute: ArchitectureDeploymentRoute,
  ArchitectureSecurityRoute: ArchitectureSecurityRoute,
  MeetingsIdRoute: MeetingsIdRoute,
  MeetingsNewRoute: MeetingsNewRoute,
  ArchitectureIndexRoute: ArchitectureIndexRoute,
  MeetingsIndexRoute: MeetingsIndexRoute,
  MonitoringIndexRoute: MonitoringIndexRoute,
  MonitoringTracesTraceIdRoute: MonitoringTracesTraceIdRoute,
  MonitoringTracesIndexRoute: MonitoringTracesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
