import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API = import.meta.env.VITE_API_BASE_URL || (window.location.port === '5173' ? 'http://localhost:8000' : window.location.origin);
const demo = { customer: 'customer@resolveai.demo', approver: 'manager@resolveai.demo', password: 'DemoPass!23' };

async function call(path, method = 'GET', token, body) {
  const response = await fetch(`${API}${path}`, { method, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) }, body: body ? JSON.stringify(body) : undefined });
  const data = await response.json();
  if (!response.ok) throw new Error(data.detail || 'Request failed');
  return data;
}

function Status({ value }) { return <span className={`status ${value.toLowerCase()}`}>{value.replaceAll('_', ' ')}</span>; }

function Login({ onLogin }) {
  const [email, setEmail] = useState(demo.customer); const [password, setPassword] = useState(demo.password); const [error, setError] = useState('');
  async function submit(e) { e.preventDefault(); try { setError(''); onLogin(await call('/api/auth/login', 'POST', null, { email, password })); } catch (err) { setError(err.message); } }
  return <main className="auth"><section className="hero"><p className="eyebrow">GOVERNED MULTI-AGENT SUPPORT</p><h1>Resolve customer issues with accountability.</h1><p>Each request is classified, checked against verified order data, investigated, and—when necessary—held for a human decision.</p><div className="flow"><span>Classify</span><span>Retrieve</span><span>Investigate</span><span>Approve</span></div></section><form className="card login" onSubmit={submit}><h2>Welcome back</h2><p>Sign in with a demo account.</p><label>Email<input value={email} onChange={e => setEmail(e.target.value)} /></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} /></label>{error && <p className="error">{error}</p>}<button>Sign in</button><button type="button" className="secondary" onClick={() => setEmail(demo.approver)}>Use approver demo</button><small>Customer: customer@resolveai.demo<br/>Approver: manager@resolveai.demo<br/>Password: DemoPass!23</small></form></main>;
}

function Dashboard({ data }) { if (!data) return null; const cards = [['Total tickets', data.total_tickets], ['Workflow-resolved', `${data.workflow_resolved_rate}%`], ['Avg. workflow', `${data.average_workflow_ms} ms`], ['Escalation rate', `${data.escalation_rate}%`]]; return <section className="dashboard"><h2>Operations dashboard</h2><div className="metrics">{cards.map(([label, value]) => <article className="metric" key={label}><span>{label}</span><strong>{value}</strong></article>)}</div><div className="dashboard-bottom"><article className="card"><h3>Ticket status</h3>{Object.entries(data.status_counts).map(([name, count]) => <div className="barrow" key={name}><span>{name.replaceAll('_', ' ')}</span><b>{count}</b><i style={{ width: `${data.total_tickets ? count / data.total_tickets * 100 : 0}%` }} /></div>)}</article><article className="card"><h3>Control signals</h3><p>Tool success: <b>{data.tool_success_rate}%</b></p><p>Pending approvals: <b>{data.pending_approvals}</b></p><p>Audit events: <b>{data.audit_events}</b></p><p>Estimated token use: <b>{data.estimated_tokens}</b></p><p>Estimated cost: <b>${data.estimated_cost_usd}</b></p></article></div></section>; }

function TicketForm({ token, onTicket }) { const [order_id, setOrder] = useState('ORD-1001'); const [message, setMessage] = useState('My laptop arrived with a damaged screen. I want a replacement.'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); async function submit(e) { e.preventDefault(); setBusy(true); try { setError(''); onTicket(await call('/api/tickets', 'POST', token, { order_id, message })); } catch (err) { setError(err.message); } finally { setBusy(false); } } return <form className="card ticket-form" onSubmit={submit}><h2>How can we help?</h2><p>Submit a support request. Sensitive outcomes always need human approval.</p><label>Order ID<input value={order_id} onChange={e => setOrder(e.target.value)} placeholder="ORD-1001" /></label><label>Describe the issue<textarea value={message} onChange={e => setMessage(e.target.value)} rows="4" /></label>{error && <p className="error">{error}</p>}<button disabled={busy}>{busy ? 'Running workflow…' : 'Create support ticket'}</button></form>; }

function TicketList({ tickets, user, token, reload }) { const [note, setNote] = useState('Verified order and policy eligibility.'); async function decide(id, decision) { try { await call(`/api/tickets/${id}/approval`, 'POST', token, { decision, note }); reload(); } catch (e) { alert(e.message); } } return <section className="ticket-list"><h2>{user.role === 'customer' ? 'Your tickets' : 'Support queue'}</h2>{tickets.length === 0 ? <div className="empty">No tickets yet. Create one using the form above.</div> : tickets.map(ticket => <article className="card ticket" key={ticket.id}><div className="ticket-head"><div><small>{ticket.id} · {ticket.order_id}</small><h3>{ticket.issue_type.replaceAll('_', ' ')}</h3></div><Status value={ticket.status} /></div><p>{ticket.customer_response}</p>{ticket.proposed_action && <p><b>Proposed action:</b> {ticket.proposed_action}</p>}<details><summary>Workflow trace ({ticket.traces.length} steps)</summary>{ticket.traces.map((trace, index) => <div className="trace" key={index}><b>{index + 1}. {trace.agent}</b><span>{trace.outcome.replaceAll('_', ' ')}</span></div>)}</details>{user.role === 'approver' && ticket.status === 'PENDING_APPROVAL' && <div className="approval"><input value={note} onChange={e => setNote(e.target.value)} /><button onClick={() => decide(ticket.id, 'approve')}>Approve</button><button className="danger" onClick={() => decide(ticket.id, 'reject')}>Reject</button></div>}</article>)}</section>; }

function App() { const [session, setSession] = useState(null); const [tickets, setTickets] = useState([]); const [dashboard, setDashboard] = useState(null); const load = async () => { if (!session) return; const token = session.access_token; setTickets(await call('/api/tickets', 'GET', token)); if (session.user.role !== 'customer') setDashboard(await call('/api/dashboard', 'GET', token)); }; useEffect(() => { load().catch(console.error); }, [session]); if (!session) return <Login onLogin={setSession} />; const isCustomer = session.user.role === 'customer'; return <><header><div className="brand">Resolve<span>AI</span></div><p>{session.user.name} · <b>{session.user.role.replace('_', ' ')}</b></p><button className="secondary" onClick={() => setSession(null)}>Sign out</button></header><main className="app"><section className="intro"><p className="eyebrow">CUSTOMER SUPPORT CONTROL CENTER</p><h1>{isCustomer ? 'Get a clear answer, safely.' : 'Keep customer resolutions moving.'}</h1><p>Every decision is policy-checked, traceable, and human-governed.</p></section>{isCustomer && <TicketForm token={session.access_token} onTicket={async () => load()} />}{!isCustomer && <Dashboard data={dashboard} />}<TicketList tickets={tickets} user={session.user} token={session.access_token} reload={load} /></main></>; }

createRoot(document.getElementById('root')).render(<App />);
