import { useCallback, useEffect, useState, type FormEvent, type ReactNode } from "react";
import { Link, useNavigate, useRouterState } from "@tanstack/react-router";
import { Activity, BarChart3, Bell, BookOpen, CalendarDays, Check, CheckCircle2, ChevronLeft, ChevronRight, Circle, Code2, Focus, LayoutDashboard, ListChecks, Menu, MoreHorizontal, Network, NotebookPen, Pause, Play, Plus, RotateCcw, Search, Settings, ShieldCheck, Sparkles, Trash2, UserRound, Workflow, X } from "lucide-react";
import { format, isToday, isBefore, startOfDay, subDays } from "date-fns";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import type { Tables } from "@/integrations/supabase/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";

export type PageKind = "dashboard"|"tasks"|"planner"|"focus"|"notes"|"analytics"|"profile"|"architecture"|"workflows"|"deployment"|"security"|"monitoring"|"traces";
type Task = Tables<"tasks">; type Note = Tables<"notes">; type Study = Tables<"study_sessions">; type FocusSession = Tables<"focus_sessions">; type Profile = Tables<"profiles">;
const workNav = [["/", "Dashboard", LayoutDashboard],["/tasks","Tasks",ListChecks],["/planner","Study Planner",CalendarDays],["/focus","Focus Timer",Focus],["/notes","Notes",NotebookPen],["/analytics","Analytics",BarChart3],["/profile","Profile",UserRound]] as const;
const systemNav = [["/architecture","Architecture",Network],["/architecture/workflows","Workflows",Workflow],["/architecture/deployment","Deployment",Code2],["/architecture/security","Security",ShieldCheck]] as const;
const monitorNav = [["/monitoring","Monitoring",Activity],["/monitoring/traces","Trace Inspector",Sparkles]] as const;

export function Workspace({ page }: { page: PageKind }) {
  const navigate = useNavigate(); const pathname = useRouterState({select:s=>s.location.pathname});
  const [mobileNav,setMobileNav]=useState(false); const [collapsed,setCollapsed]=useState(false);
  const [user,setUser]=useState<{id:string;email:string} | null>(null); const [profile,setProfile]=useState<Profile|null>(null);
  const [tasks,setTasks]=useState<Task[]>([]); const [notes,setNotes]=useState<Note[]>([]); const [studies,setStudies]=useState<Study[]>([]); const [focusSessions,setFocusSessions]=useState<FocusSession[]>([]); const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{ setLoading(true); const {data:{user:u}}=await supabase.auth.getUser(); if(!u){setLoading(false);return;} setUser({id:u.id,email:u.email??""});
    const [p,t,n,s,f]=await Promise.all([supabase.from("profiles").select("*").eq("id",u.id).maybeSingle(),supabase.from("tasks").select("*").order("created_at",{ascending:false}),supabase.from("notes").select("*").order("is_pinned",{ascending:false}).order("updated_at",{ascending:false}),supabase.from("study_sessions").select("*").order("starts_at"),supabase.from("focus_sessions").select("*").order("completed_at",{ascending:false})]);
    let resolved=p.data; if(!resolved){const created={id:u.id,email:u.email??"",full_name:String(u.user_metadata?.['full_name']??u.email?.split("@")[0]??"Student")}; const result=await supabase.from("profiles").upsert(created).select().single(); resolved=result.data;} setProfile(resolved); setTasks(t.data??[]);setNotes(n.data??[]);setStudies(s.data??[]);setFocusSessions(f.data??[]);setLoading(false);
  },[]);
  useEffect(()=>{void load()},[load]);
  async function signOut(){await supabase.auth.signOut();await navigate({to:"/login"});}
  const titleMap:Record<PageKind,string>={dashboard:"Dashboard",tasks:"Tasks",planner:"Study Planner",focus:"Focus Timer",notes:"Notes",analytics:"Analytics",profile:"Profile",architecture:"System Architecture",workflows:"Workflow Diagrams",deployment:"Deployment Pipeline",security:"Security Model",monitoring:"Application Monitoring",traces:"Trace Inspector"};
  const name=profile?.full_name||"Student"; const initials=name.split(" ").map(x=>x[0]).join("").slice(0,2).toUpperCase();
  return <div className="app-frame">
    <aside className={`sidebar ${collapsed?"sidebar-collapsed":""} ${mobileNav?"sidebar-mobile-open":""}`}>
      <div className="sidebar-brand"><span className="brand-mark"><BookOpen/></span>{!collapsed&&<strong>Taskora</strong>}<Button variant="ghost" size="icon" className="sidebar-close" onClick={()=>setMobileNav(false)}><X/></Button></div>
      <NavGroup label="Workspace" items={workNav} pathname={pathname} collapsed={collapsed}/><NavGroup label="System design" items={systemNav} pathname={pathname} collapsed={collapsed}/><NavGroup label="Observability" items={monitorNav} pathname={pathname} collapsed={collapsed}/>
      <div className="sidebar-bottom">{!collapsed&&<p>Protected workspace<br/><span>Lovable Cloud</span></p>}<Button variant="ghost" size="icon" onClick={()=>setCollapsed(!collapsed)} aria-label="Collapse sidebar">{collapsed?<ChevronRight/>:<ChevronLeft/>}</Button></div>
    </aside>
    {mobileNav&&<div className="nav-scrim" onClick={()=>setMobileNav(false)}/>} 
    <div className="workspace">
      <header className="topbar"><div className="topbar-left"><Button variant="ghost" size="icon" className="mobile-menu" onClick={()=>setMobileNav(true)}><Menu/></Button><span className="crumb">Workspace</span><span>/</span><strong>{titleMap[page]}</strong></div><div className="topbar-actions"><div className="search-mini"><Search/><span>Search</span><kbd>⌘K</kbd></div><Button variant="ghost" size="icon" aria-label="Notifications"><Bell/></Button><DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" className="profile-trigger"><span className="avatar">{initials}</span><span>{name}</span></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem asChild><Link to="/profile"><Settings/> Profile settings</Link></DropdownMenuItem><DropdownMenuSeparator/><DropdownMenuItem onClick={signOut}>Log out</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></header>
      <main className="page"><div className="page-heading"><div><p className="eyebrow">{format(new Date(),"EEEE d MMMM, yyyy")}</p><h1>{page==="dashboard"?`Welcome back, ${name.split(" ")[0]}`:titleMap[page]}</h1><p className="subtle">{subtitle(page,tasks,studies)}</p></div>{["dashboard","tasks"].includes(page)&&<TaskDialog userId={user?.id} onDone={load}/>}</div>
      {loading?<Loading/>:<Page page={page} user={user} profile={profile} tasks={tasks} notes={notes} studies={studies} focusSessions={focusSessions} reload={load}/>}</main>
    </div>
  </div>
}
function NavGroup({label,items,pathname,collapsed}:{label:string;items:readonly (readonly [string,string,typeof LayoutDashboard])[];pathname:string;collapsed:boolean}){return <div className="nav-group">{!collapsed&&<p>{label}</p>}<nav>{items.map(([to,labelText,Icon])=><Link key={to} to={to} className={`nav-link ${pathname===to?"active":""}`} title={collapsed?labelText:undefined}><Icon/>{!collapsed&&<span>{labelText}</span>}</Link>)}</nav></div>}
function subtitle(page:PageKind,tasks:Task[],studies:Study[]){if(page==="dashboard")return `${tasks.filter(t=>t.status!=="completed"&&t.due_at&&isBefore(new Date(t.due_at),startOfDay(new Date()))).length} overdue · ${tasks.filter(t=>t.priority==="high"&&t.status!=="completed").length} high priority · ${studies.filter(s=>isToday(new Date(s.starts_at))).length} sessions today`; const map:Partial<Record<PageKind,string>>={tasks:"Capture assignments, prioritize clearly, finish calmly.",planner:"Shape a realistic week and catch schedule conflicts early.",focus:"Protect a block of attention and build your focus history.",notes:"Collect ideas, course notes, and revision material.",analytics:"Patterns from your own completed work and study time.",profile:"Personal details, preferences, theme, and security.",architecture:"Seven layers behind Taskora’s student experience.",workflows:"Deterministic application flows and their operational states.",deployment:"Documented release stages; not a claim of production deployment.",security:"Implemented controls and proposed safeguards, clearly separated.",monitoring:"Demo operational signals alongside genuine workspace counts.",traces:"Searchable sample workflow traces for academic demonstration."};return map[page]??""}
function Loading(){return <div className="loading-grid">{Array.from({length:6}).map((_,i)=><div className="skeleton-card" key={i}/>)}</div>}
function Page(props:{page:PageKind;user:{id:string;email:string}|null;profile:Profile|null;tasks:Task[];notes:Note[];studies:Study[];focusSessions:FocusSession[];reload:()=>Promise<void>}){switch(props.page){case"dashboard":return <Dashboard {...props}/>;case"tasks":return <Tasks {...props}/>;case"planner":return <Planner {...props}/>;case"focus":return <FocusPage {...props}/>;case"notes":return <Notes {...props}/>;case"analytics":return <Analytics {...props}/>;case"profile":return <ProfilePage {...props}/>;default:return <Technical page={props.page} counts={{tasks:props.tasks.length,notes:props.notes.length,sessions:props.studies.length}}/>}}
function Stat({label,value,detail,icon}:{label:string;value:string;detail:string;icon:ReactNode}){return <div className="stat-card"><div className="stat-top"><span>{label}</span><i>{icon}</i></div><strong>{value}</strong><small>{detail}</small></div>}
function Dashboard({tasks,studies,focusSessions,profile,reload,user}:Parameters<typeof Page>[0]){const done=tasks.filter(t=>t.status==="completed").length;const overdue=tasks.filter(t=>t.status!=="completed"&&t.due_at&&isBefore(new Date(t.due_at),startOfDay(new Date()))).length;const todayFocus=focusSessions.filter(f=>isToday(new Date(f.completed_at))).reduce((a,b)=>a+b.duration_minutes,0);const todayStudy=studies.filter(s=>s.status==="completed"&&isToday(new Date(s.starts_at))).reduce((a,b)=>a+b.duration_minutes,0);const goal=profile?.study_goal_minutes??180;return <><div className="stats-grid"><Stat label="Tasks completed" value={`${done}/${tasks.length}`} detail={`${tasks.length?Math.round(done/tasks.length*100):0}% completion`} icon={<CheckCircle2/>}/><Stat label="Overdue" value={String(overdue)} detail="needs attention" icon={<Bell/>}/><Stat label="Focus today" value={`${todayFocus}m`} detail={`${focusSessions.reduce((a,b)=>a+b.duration_minutes,0)}m all time`} icon={<Focus/>}/><Stat label="Study goal" value={`${Math.min(100,Math.round((todayFocus+todayStudy)/goal*100))}%`} detail={`${todayFocus+todayStudy} / ${goal} min`} icon={<Sparkles/>}/></div><div className="dashboard-grid"><section className="panel span-2"><PanelTitle title="Today's priorities" link="/tasks"/><TaskList tasks={tasks.filter(t=>t.status!=="completed").slice(0,5)} reload={reload}/></section><section className="panel"><PanelTitle title="Upcoming sessions" link="/planner"/><SessionList studies={studies.slice(0,5)}/></section><section className="panel span-2"><PanelTitle title="Weekly momentum"/><WeeklyBars tasks={tasks} focusSessions={focusSessions}/></section><section className="panel"><PanelTitle title="Quick capture"/><div className="quick-grid"><TaskDialog userId={user?.id} onDone={reload} compact/><Link className="quick-action" to="/notes"><NotebookPen/>New note</Link><Link className="quick-action" to="/focus"><Focus/>Start focus</Link></div></section></div></>}
function PanelTitle({title,link}:{title:string;link?:string}){return <div className="panel-title"><h2>{title}</h2>{link?<Link to={link}>View all</Link>:null}</div>}
function TaskList({tasks,reload}:{tasks:Task[];reload:()=>Promise<void>}){async function toggle(t:Task){await supabase.from("tasks").update({status:t.status==="completed"?"todo":"completed",completed_at:t.status==="completed"?null:new Date().toISOString()}).eq("id",t.id);await reload()}return <div className="list">{tasks.length?tasks.map(t=><div className="task-row" key={t.id}><Button variant="ghost" size="icon" onClick={()=>toggle(t)} aria-label="Toggle task">{t.status==="completed"?<CheckCircle2/>:<Circle/>}</Button><div><strong className={t.status==="completed"?"done":""}>{t.title}</strong><small>{t.course||"General"}{t.due_at?` · ${format(new Date(t.due_at),"d MMM")}`:""}</small></div><span className={`priority ${t.priority}`}>{t.priority}</span></div>):<Empty icon={<ListChecks/>} title="No tasks yet" text="Add your first assignment to begin planning."/>}</div>}
function SessionList({studies}:{studies:Study[]}){return <div className="list">{studies.length?studies.map(s=><div className="session-row" key={s.id}><div><strong>{s.course}</strong><small>{s.topic}</small></div><span>{format(new Date(s.starts_at),"d MMM · HH:mm")}<small>{s.duration_minutes}m</small></span></div>):<Empty icon={<CalendarDays/>} title="No sessions planned" text="Build your week in the planner."/>}</div>}
function WeeklyBars({tasks,focusSessions}:{tasks:Task[];focusSessions:FocusSession[]}){const days=Array.from({length:7},(_,i)=>subDays(new Date(),6-i));return <div className="bars">{days.map(day=>{const v=tasks.filter(t=>t.completed_at&&format(new Date(t.completed_at),"yyyy-MM-dd")===format(day,"yyyy-MM-dd")).length+focusSessions.filter(f=>format(new Date(f.completed_at),"yyyy-MM-dd")===format(day,"yyyy-MM-dd")).length;return <div key={day.toISOString()}><div className="bar-track"><span style={{height:`${Math.max(5,Math.min(100,v*22))}%`}}/></div><small>{format(day,"EEE")}</small></div>})}</div>}
function Tasks({tasks,reload}:Parameters<typeof Page>[0]){const [q,setQ]=useState("");const [filter,setFilter]=useState("all");const visible=tasks.filter(t=>(filter==="all"||t.status===filter||t.priority===filter)&&t.title.toLowerCase().includes(q.toLowerCase()));async function remove(id:string){if(!confirm("Delete this task?"))return;await supabase.from("tasks").delete().eq("id",id);toast.success("Task deleted");await reload()}return <section className="panel"><div className="toolbar"><div className="search-field"><Search/><Input placeholder="Search tasks" value={q} onChange={e=>setQ(e.target.value)}/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All tasks</option><option value="todo">To do</option><option value="in_progress">In progress</option><option value="completed">Completed</option><option value="high">High priority</option></select></div>{visible.length?<div className="table-list">{visible.map(t=><div className="table-row" key={t.id}><div className={`status-dot ${t.status}`}/><div className="grow"><strong>{t.title}</strong><small>{t.description||"No description"}</small></div><span>{t.course||"General"}</span><span className={`priority ${t.priority}`}>{t.priority}</span><span>{t.due_at?format(new Date(t.due_at),"d MMM, HH:mm"):"No due date"}</span><Button variant="ghost" size="icon" onClick={()=>remove(t.id)}><Trash2/></Button></div>)}</div>:<Empty icon={<ListChecks/>} title="Nothing matches" text="Try another filter or add a new task."/>}</section>}
function TaskDialog({userId,onDone,compact=false}:{userId:string|undefined;onDone:()=>Promise<void>;compact?:boolean}){const [open,setOpen]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!userId)return;const fd=new FormData(e.currentTarget);const {error}=await supabase.from("tasks").insert({user_id:userId,title:String(fd.get("title")),course:String(fd.get("course")??""),priority:String(fd.get("priority")??"medium"),due_at:fd.get("due")?new Date(String(fd.get("due"))).toISOString():null});if(error)toast.error(error.message);else{toast.success("Task added");setOpen(false);await onDone()}}return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild>{compact?<button className="quick-action"><Plus/>New task</button>:<Button><Plus/> New task</Button>}</DialogTrigger><DialogContent><DialogHeader><DialogTitle>Add a task</DialogTitle><DialogDescription>Capture the next clear action.</DialogDescription></DialogHeader><form className="dialog-form" onSubmit={submit}><div><Label htmlFor="task-title">Title</Label><Input id="task-title" name="title" required autoFocus/></div><div><Label htmlFor="course">Course</Label><Input id="course" name="course"/></div><div className="form-grid"><div><Label htmlFor="priority">Priority</Label><select id="priority" name="priority"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></div><div><Label htmlFor="due">Due</Label><Input id="due" name="due" type="datetime-local"/></div></div><Button type="submit">Add task</Button></form></DialogContent></Dialog>}
function Planner({studies,user,reload}:Parameters<typeof Page>[0]){async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!user)return;const f=new FormData(e.currentTarget);const start=new Date(String(f.get("start")));const duration=Number(f.get("duration"));const overlap=studies.some(s=>{const a=new Date(s.starts_at).getTime(),b=a+s.duration_minutes*60000;return start.getTime()<b&&start.getTime()+duration*60000>a});if(overlap){toast.error("This session overlaps with another plan.");return}await supabase.from("study_sessions").insert({user_id:user.id,course:String(f.get("course")),topic:String(f.get("topic")),starts_at:start.toISOString(),duration_minutes:duration});toast.success("Study session planned");e.currentTarget.reset();await reload()}return <div className="two-column"><section className="panel"><PanelTitle title="Plan a session"/><form className="dialog-form" onSubmit={add}><div><Label>Course</Label><Input name="course" required/></div><div><Label>Topic</Label><Input name="topic" required/></div><div className="form-grid"><div><Label>Starts</Label><Input name="start" type="datetime-local" required/></div><div><Label>Minutes</Label><Input name="duration" type="number" min="5" max="720" defaultValue="60" required/></div></div><Button><Plus/>Add to planner</Button></form></section><section className="panel"><PanelTitle title="Schedule"/><SessionList studies={studies}/></section></div>}
function FocusPage({user,focusSessions,reload,profile}:Parameters<typeof Page>[0]){const initial=(profile?.focus_duration??25)*60;const [seconds,setSeconds]=useState(initial);const [running,setRunning]=useState(false);useEffect(()=>{if(!running)return;const id=setInterval(()=>setSeconds(s=>{if(s<=1){setRunning(false);return 0}return s-1}),1000);return()=>clearInterval(id)},[running]);async function save(){if(!user)return;const mins=Math.max(1,Math.round((initial-seconds)/60));await supabase.from("focus_sessions").insert({user_id:user.id,duration_minutes:mins});toast.success("Focus session saved");setSeconds(initial);await reload()}return <div className="focus-layout"><section className="timer-panel"><p className="eyebrow">Deep work</p><div className="timer-ring"><strong>{String(Math.floor(seconds/60)).padStart(2,"0")}:{String(seconds%60).padStart(2,"0")}</strong><span>{running?"Focus in progress":"Ready when you are"}</span></div><div className="timer-controls"><Button size="lg" onClick={()=>setRunning(!running)}>{running?<><Pause/>Pause</>:<><Play/>Start</>}</Button><Button variant="outline" size="icon" onClick={()=>{setRunning(false);setSeconds(initial)}}><RotateCcw/></Button>{seconds<initial&&<Button variant="secondary" onClick={save}><Check/>Save session</Button>}</div></section><section className="panel"><PanelTitle title="Recent focus"/><div className="list">{focusSessions.slice(0,8).map(f=><div className="session-row" key={f.id}><div><strong>{f.duration_minutes} minutes</strong><small>Completed focus block</small></div><span>{format(new Date(f.completed_at),"d MMM")}</span></div>)}</div></section></div>}
function Notes({notes,user,reload}:Parameters<typeof Page>[0]){const [q,setQ]=useState("");const visible=notes.filter(n=>(n.title+n.content+n.tags.join(" ")).toLowerCase().includes(q.toLowerCase()));async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!user)return;const f=new FormData(e.currentTarget);await supabase.from("notes").insert({user_id:user.id,title:String(f.get("title")),content:String(f.get("content")),tags:String(f.get("tags")||"").split(",").map(x=>x.trim()).filter(Boolean)});toast.success("Note saved");e.currentTarget.reset();await reload()}async function pin(note:Note){await supabase.from("notes").update({is_pinned:!note.is_pinned}).eq("id",note.id);await reload()}return <><div className="toolbar"><div className="search-field"><Search/><Input placeholder="Search notes and tags" value={q} onChange={e=>setQ(e.target.value)}/></div></div><div className="notes-grid"><form className="note-compose" onSubmit={add}><Input name="title" placeholder="Note title" required/><Textarea name="content" placeholder="Start writing…" rows={6}/><Input name="tags" placeholder="Tags, separated by commas"/><Button><Plus/>Save note</Button></form>{visible.map(n=><article className="note-card" key={n.id}><div className="note-top"><div>{n.is_pinned&&<span className="pin">Pinned</span>}<h2>{n.title}</h2></div><Button variant="ghost" size="icon" onClick={()=>pin(n)}><MoreHorizontal/></Button></div><p>{n.content||"Empty note"}</p><div className="tags">{n.tags.map(t=><span key={t}>{t}</span>)}</div><small>Updated {format(new Date(n.updated_at),"d MMM, HH:mm")}</small></article>)}</div></>}
function Analytics({tasks,studies,focusSessions}:Parameters<typeof Page>[0]){const done=tasks.filter(t=>t.status==="completed").length;const focus=focusSessions.reduce((a,b)=>a+b.duration_minutes,0);const study=studies.filter(s=>s.status==="completed").reduce((a,b)=>a+b.duration_minutes,0);const priorities=["high","medium","low"].map(p=>({p,n:tasks.filter(t=>t.priority===p).length}));return <><div className="stats-grid three"><Stat label="Completion rate" value={`${tasks.length?Math.round(done/tasks.length*100):0}%`} detail={`${done} of ${tasks.length} tasks`} icon={<CheckCircle2/>}/><Stat label="Focused" value={`${focus}m`} detail={`${focusSessions.length} sessions`} icon={<Focus/>}/><Stat label="Study time" value={`${study}m`} detail={`${studies.filter(s=>s.status==="completed").length} completed plans`} icon={<BookOpen/>}/></div><div className="two-column"><section className="panel"><PanelTitle title="Task mix"/><div className="priority-bars">{priorities.map(x=><div key={x.p}><span>{x.p}</span><div><i style={{width:`${tasks.length?x.n/tasks.length*100:0}%`}}/></div><strong>{x.n}</strong></div>)}</div></section><section className="panel"><PanelTitle title="What this shows"/><p className="prose">These charts use only your account’s saved tasks, completed study sessions, and focus history. They update whenever your workspace changes.</p></section></div></>}
function ProfilePage({profile,user,reload}:Parameters<typeof Page>[0]){async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!user)return;const f=new FormData(e.currentTarget);await supabase.from("profiles").update({full_name:String(f.get("name")),course:String(f.get("course")),study_goal_minutes:Number(f.get("goal")),theme:String(f.get("theme")),email_reminders:f.get("reminders")==="on",focus_duration:Number(f.get("focus")),break_duration:Number(f.get("break"))}).eq("id",user.id);toast.success("Profile updated");await reload()}return <div className="two-column profile-layout"><section className="panel"><PanelTitle title="Personal information"/><form className="dialog-form" onSubmit={save}><div><Label>Full name</Label><Input name="name" defaultValue={profile?.full_name}/></div><div><Label>Email</Label><Input value={user?.email??""} disabled/></div><div><Label>Course or program</Label><Input name="course" defaultValue={profile?.course}/></div><div><Label>Daily study goal (minutes)</Label><Input name="goal" type="number" min="15" max="1440" defaultValue={profile?.study_goal_minutes}/></div><div className="form-grid"><div><Label>Focus length</Label><Input name="focus" type="number" min="1" max="180" defaultValue={profile?.focus_duration}/></div><div><Label>Break length</Label><Input name="break" type="number" min="1" max="60" defaultValue={profile?.break_duration}/></div></div><div><Label>Theme preference</Label><select name="theme" defaultValue={profile?.theme}><option value="light">Light</option><option value="dark">Dark</option><option value="system">System</option></select></div><label className="check-row"><input name="reminders" type="checkbox" defaultChecked={profile?.email_reminders}/>Email reminders</label><Button>Save changes</Button></form></section><section className="panel"><PanelTitle title="Account security"/><div className="security-callout"><ShieldCheck/><div><strong>Protected student workspace</strong><p>Your records are isolated at the database level and available only to your signed-in account.</p></div></div><Button variant="outline" asChild><Link to="/forgot-password">Change password securely</Link></Button></section></div>}
function Empty({icon,title,text}:{icon:ReactNode;title:string;text:string}){return <div className="empty">{icon}<strong>{title}</strong><p>{text}</p></div>}
const layers=["User","Experience","AI / application orchestration","Agent / workflow","Application services","Data","External integrations"];
const workflows=["Task management","Study planning","Focus sessions","Notes","Analytics","Reminders"];
function Technical({page,counts}:{page:PageKind;counts:{tasks:number;notes:number;sessions:number}}){if(page==="architecture")return <div className="architecture-stack">{layers.map((l,i)=><div key={l} className="layer"><span>{String(i+1).padStart(2,"0")}</span><strong>{l}</strong><p>{["Students and account identity","Responsive workspace, routes, and feedback","Deterministic demo mode; real AI not configured","Validation, state transitions, and fallback paths","Tasks, notes, planner, focus, and analytics","Private account-owned records with access policies","Managed sign-in and future notification providers"][i]}</p></div>)}</div>;
if(page==="workflows")return <div className="workflow-grid">{workflows.map((w,i)=><article className="panel" key={w}><div className="panel-title"><h2>{w}</h2><span className="demo-badge">Demo flow</span></div><div className="state-flow">{["IDLE","PROCESSING","VALIDATING",i===5?"FALLBACK":"COMPLETED"].map((s,j)=><span className={j===3?"good":""} key={s}>{s}</span>)}</div><p className="prose">A deterministic representation for academic review. This is not live telemetry.</p></article>)}</div>;
if(page==="deployment")return <div className="pipeline">{["Development","Testing / staging","Preview","Production"].map((x,i)=><article className="pipeline-step" key={x}><span>{i+1}</span><div><h2>{x}</h2><p>{i===0?"Local feature work and validation":i===1?"Automated checks and scenario review":i===2?"Interactive stakeholder verification":"Release only after checklist approval"}</p><ul><li>Environment configuration</li><li>Health check</li><li>{i===3?"Rollback documented":"Quality gate"}</li></ul></div><b className={i===2?"status-live":"status-doc"}>{i===2?"Current preview":"Documented"}</b></article>)}</div>;
if(page==="security")return <div className="security-grid"><section className="panel"><h2>Implemented controls</h2>{["Managed email and Google authentication","Protected application routes","Per-account database ownership policies","Validated inputs and private secrets","Password leak screening"].map(x=><p className="control" key={x}><CheckCircle2/>{x}</p>)}</section><section className="panel"><h2>Proposed / not verified</h2>{["Independent penetration test","Institutional SSO","Formal incident response exercise","Production disaster recovery drill"].map(x=><p className="control proposed" key={x}><Circle/>{x}</p>)}</section></div>;
if(page==="monitoring")return <><div className="stats-grid three"><Stat label="Workspace records" value={String(counts.tasks+counts.notes+counts.sessions)} detail="Genuine account count" icon={<Activity/>}/><Stat label="Workflow health" value="6 / 6" detail="Demo status signals" icon={<Workflow/>}/><Stat label="Safety checks" value="5" detail="Documented controls" icon={<ShieldCheck/>}/></div><section className="panel"><div className="panel-title"><h2>Operational overview</h2><span className="demo-badge">Demo data</span></div><div className="health-list">{workflows.map((w,i)=><div key={w}><span className={`health-dot ${i===5?"warning":""}`}/><strong>{w}</strong><span>{i===5?"Fallback":"Healthy"}</span><small>{20+i*7}ms sample</small></div>)}</div></section></>;
return <section className="panel"><div className="toolbar"><div className="search-field"><Search/><Input placeholder="Search sample traces"/></div><span className="demo-badge">Sample events</span></div><div className="trace-list">{workflows.map((w,i)=><details key={w}><summary><span className="trace-id">TR-{1042+i}</span><strong>{w}</strong><span>{i===5?"FALLBACK":"COMPLETED"}</span><small>{48+i*19}ms</small></summary><pre>{JSON.stringify({traceId:`tr_${1042+i}`,workflow:w,state:i===5?"FALLBACK":"COMPLETED",spans:[{name:"validate_input",duration_ms:8},{name:"apply_rules",duration_ms:25+i*4},{name:"persist_result",duration_ms:15}]},null,2)}</pre></details>)}</div></section>}
