import {motion,AnimatePresence,useReducedMotion} from 'motion/react'; import {useEffect,useState} from 'react'; import type {ReactNode} from 'react';
export function TextEffect({children,className='',delay=0}:{children:string,className?:string,delay?:number}){return <motion.div initial="hidden" animate="show" variants={{hidden:{opacity:0},show:{opacity:1,transition:{staggerChildren:.035,delayChildren:delay}}}} className={className}>{children.split(' ').map((w,i)=><motion.span key={i} className="inline-block mr-[.28em]" variants={{hidden:{opacity:0,y:8,filter:'blur(8px)'},show:{opacity:1,y:0,filter:'blur(0px)',transition:{duration:.45}}}}>{w}</motion.span>)}</motion.div>}
export function TextScramble({children}:{children:string}){return <motion.span initial={{opacity:0}} animate={{opacity:1}} transition={{duration:.3}}>{children}</motion.span>}
export function TextShimmer({children}:{children:string}){return <motion.span className="bg-[linear-gradient(90deg,var(--muted),#fff,var(--muted))] bg-[length:200%_100%] bg-clip-text text-transparent" animate={{backgroundPosition:['200% 0','-20% 0']}} transition={{duration:1.8,repeat:Infinity,ease:'linear'}}>{children}</motion.span>}
export function TextLoop({children,interval=2,className=''}:{children:ReactNode[];interval?:number;className?:string}){const items=children.filter(Boolean);const [index,setIndex]=useState(0);useEffect(()=>{if(items.length<2)return;const id=window.setInterval(()=>setIndex(i=>(i+1)%items.length),interval*1000);return()=>window.clearInterval(id)},[items.length,interval]);return <span className={`relative inline-flex min-h-[1.25em] items-center ${className}`}><AnimatePresence mode="popLayout" initial={false}><motion.span key={index} initial={{opacity:0,y:8,filter:'blur(6px)'}} animate={{opacity:1,y:0,filter:'blur(0px)'}} exit={{opacity:0,y:-8,filter:'blur(6px)'}} transition={{duration:.32}}>{items[index]}</motion.span></AnimatePresence></span>}
export function Spotlight({children,className=''}:{children:ReactNode,className?:string}){return <div className={`relative overflow-hidden ${className}`}><motion.div className="pointer-events-none absolute -top-32 left-1/2 h-72 w-72 -translate-x-1/2 rounded-full bg-accent/10 blur-3xl" animate={{x:['-30%','30%','-30%']}} transition={{duration:8,repeat:Infinity}}/>{children}</div>}
export function GlowEffect({children,className=''}:{children:ReactNode,className?:string}){return <motion.div className={className} whileHover={{filter:'drop-shadow(0 0 22px rgba(0,229,255,.28))'}}>{children}</motion.div>}
export function BorderTrail({children,active=true}:{children:ReactNode,active?:boolean}){return <div className="relative">{active&&<motion.div className="absolute -inset-px rounded-[inherit] bg-[conic-gradient(from_0deg,transparent,rgba(0,229,255,.65),transparent_35%)]" animate={{rotate:360}} transition={{duration:3,repeat:Infinity,ease:'linear'}}/>}<div className="relative h-full">{children}</div></div>}
export function Tilt({children}:{children:ReactNode}){return <motion.div whileHover={{rotateX:2,rotateY:-3,y:-3}} transition={{type:'spring',stiffness:300,damping:22}} style={{transformPerspective:900}}>{children}</motion.div>}
export function Magnetic({children}:{children:ReactNode}){return <motion.div whileHover={{scale:1.025}} whileTap={{scale:.98}}>{children}</motion.div>}
export function TransitionPanel({children,id='panel'}:{children:ReactNode;id?:string}){const reduce=useReducedMotion();return <AnimatePresence mode="wait"><motion.div key={id} initial={reduce?{opacity:0}:{opacity:0,x:12}} animate={{opacity:1,x:0}} exit={reduce?{opacity:0}:{opacity:0,x:-12}} transition={{duration:reduce?.12:.28,ease:[.22,1,.36,1]}}>{children}</motion.div></AnimatePresence>}

export function AnimatedNumber({value}:{value:number}){return <motion.span key={value} initial={{y:10,opacity:0}} animate={{y:0,opacity:1}} className="serif text-4xl text-white">{value.toLocaleString()}</motion.span>}

export function Reveal({children,delay=0,className=''}:{children:ReactNode,delay?:number,className?:string}){return <motion.div className={className} initial={{opacity:0,y:36,filter:'blur(8px)'}} whileInView={{opacity:1,y:0,filter:'blur(0px)'}} viewport={{once:true,amount:.25}} transition={{duration:.9,delay,ease:[.22,1,.36,1]}}>{children}</motion.div>}
