import { createFileRoute } from "@tanstack/react-router";
import { useQueryClient } from "@tanstack/react-query";
import { Card, Empty, SeverityBadge } from "@/components/bits";
import { Button } from "@/components/ui/button";
import { sb, useAnomalies, useBills, useReminders } from "@/lib/data";
import { formatINR } from "@/lib/agents";
import { PageHeader } from "./route";

export const Route = createFileRoute("/_authenticated/alerts")({
  head: () => ({ meta: [{ title: "Alerts — BillPilot" }, { name: "description", content: "Reminders, overdue bills and price anomalies." }, { property: "og:title", content: "Alerts — BillPilot" }, { property: "og:description", content: "Reminders and anomalies." }] }),
  component: Alerts,
});

function Alerts() {
  const reminders = useReminders().data ?? [];
  const anomalies = useAnomalies().data ?? [];
  const bills = useBills().data ?? [];
  const qc = useQueryClient();
  const billMap = Object.fromEntries(bills.map((b) => [b.id, b]));
  const today = new Date().toISOString().slice(0, 10);
  const overdue = bills.filter((b) => b.due_date && b.due_date < today && b.status === "needs_review");
  const done = async (id: string) => { await sb.from("reminders").update({ status: "done" }).eq("id", id); qc.invalidateQueries({ queryKey: ["reminders"] }); };
  return (
    <div>
      <PageHeader title="Alerts" sub="Generated by the Anomaly Detection and Reminder & Insights agents." />
      <div className="grid gap-4 lg:grid-cols-2">
        <Card>
          <h2 className="mb-3 font-semibold">Reminders & insights</h2>
          {reminders.map((r) => (
            <div key={r.id} className={`flex items-center justify-between border-b py-3 last:border-0 ${r.status === "done" ? "opacity-50" : ""}`}>
              <div><p className="text-sm">{r.message}</p><p className="text-xs text-muted-foreground">{r.reminder_date}{r.reminder_date < today && r.status !== "done" ? " · past" : ""}</p></div>
              {r.status !== "done" && <Button size="sm" variant="ghost" onClick={() => done(r.id)}>Dismiss</Button>}
            </div>
          ))}
          {!reminders.length && <Empty>No reminders.</Empty>}
          {overdue.map((b) => <p key={b.id} className="mt-2 rounded bg-destructive/10 p-2 text-sm text-destructive">{b.merchant} is past due and still awaiting review.</p>)}
        </Card>
        <Card>
          <h2 className="mb-3 font-semibold">Anomalies</h2>
          {anomalies.map((a) => (
            <div key={a.id} className="border-b py-3 last:border-0">
              <div className="flex items-center justify-between"><p className="font-medium">{billMap[a.bill_id]?.merchant ?? "Bill"}</p><SeverityBadge s={a.severity} /></div>
              <p className="text-sm text-muted-foreground">{a.type?.replaceAll("_", " ")}: {formatINR(a.previous_amount)} → {formatINR(a.current_amount)} ({a.percentage_change > 0 ? "+" : ""}{a.percentage_change}%)</p>
            </div>
          ))}
          {!anomalies.length && <Empty>No anomalies.</Empty>}
        </Card>
      </div>
    </div>
  );
}
