/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ArchitectureIndexRouteImport } from './routes/architecture.index'
import { Route as ArchitectureAgentsRouteImport } from './routes/architecture.agents'
import { Route as ArchitectureDeploymentRouteImport } from './routes/architecture.deployment'
import { Route as ArchitectureSecurityRouteImport } from './routes/architecture.security'
import { Route as MonitoringIndexRouteImport } from './routes/monitoring.index'
import { Route as MonitoringTracesRouteImport } from './routes/monitoring.traces'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities.index'
import { Route as OpportunitiesIdRouteImport } from './routes/opportunities.$id'
import { Route as OpportunitiesNewRouteImport } from './routes/opportunities.new'
import { Route as ApiPublicHealthzRouteImport } from './routes/api/public/healthz'
import { Route as ApiPublicReadyzRouteImport } from './routes/api/public/readyz'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureIndexRoute = ArchitectureIndexRouteImport.update({
  id: '/architecture/',
  path: '/architecture/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureAgentsRoute = ArchitectureAgentsRouteImport.update({
  id: '/architecture/agents',
  path: '/architecture/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureDeploymentRoute = ArchitectureDeploymentRouteImport.update({
  id: '/architecture/deployment',
  path: '/architecture/deployment',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureSecurityRoute = ArchitectureSecurityRouteImport.update({
  id: '/architecture/security',
  path: '/architecture/security',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringIndexRoute = MonitoringIndexRouteImport.update({
  id: '/monitoring/',
  path: '/monitoring/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringTracesRoute = MonitoringTracesRouteImport.update({
  id: '/monitoring/traces',
  path: '/monitoring/traces',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdRoute = OpportunitiesIdRouteImport.update({
  id: '/opportunities/$id',
  path: '/opportunities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesNewRoute = OpportunitiesNewRouteImport.update({
  id: '/opportunities/new',
  path: '/opportunities/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthzRoute = ApiPublicHealthzRouteImport.update({
  id: '/api/public/healthz',
  path: '/api/public/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReadyzRoute = ApiPublicReadyzRouteImport.update({
  id: '/api/public/readyz',
  path: '/api/public/readyz',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/architecture/agents': typeof ArchitectureAgentsRoute
  '/architecture/deployment': typeof ArchitectureDeploymentRoute
  '/architecture/security': typeof ArchitectureSecurityRoute
  '/monitoring/traces': typeof MonitoringTracesRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/opportunities/new': typeof OpportunitiesNewRoute
  '/architecture/': typeof ArchitectureIndexRoute
  '/monitoring/': typeof MonitoringIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/api/public/healthz': typeof ApiPublicHealthzRoute
  '/api/public/readyz': typeof ApiPublicReadyzRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/architecture/agents': typeof ArchitectureAgentsRoute
  '/architecture/deployment': typeof ArchitectureDeploymentRoute
  '/architecture/security': typeof ArchitectureSecurityRoute
  '/monitoring/traces': typeof MonitoringTracesRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/opportunities/new': typeof OpportunitiesNewRoute
  '/architecture': typeof ArchitectureIndexRoute
  '/monitoring': typeof MonitoringIndexRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/api/public/healthz': typeof ApiPublicHealthzRoute
  '/api/public/readyz': typeof ApiPublicReadyzRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/architecture/agents': typeof ArchitectureAgentsRoute
  '/architecture/deployment': typeof ArchitectureDeploymentRoute
  '/architecture/security': typeof ArchitectureSecurityRoute
  '/monitoring/traces': typeof MonitoringTracesRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/opportunities/new': typeof OpportunitiesNewRoute
  '/architecture/': typeof ArchitectureIndexRoute
  '/monitoring/': typeof MonitoringIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/api/public/healthz': typeof ApiPublicHealthzRoute
  '/api/public/readyz': typeof ApiPublicReadyzRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/architecture/agents'
    | '/architecture/deployment'
    | '/architecture/security'
    | '/monitoring/traces'
    | '/opportunities/$id'
    | '/opportunities/new'
    | '/architecture/'
    | '/monitoring/'
    | '/opportunities/'
    | '/api/public/healthz'
    | '/api/public/readyz'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/architecture/agents'
    | '/architecture/deployment'
    | '/architecture/security'
    | '/monitoring/traces'
    | '/opportunities/$id'
    | '/opportunities/new'
    | '/architecture'
    | '/monitoring'
    | '/opportunities'
    | '/api/public/healthz'
    | '/api/public/readyz'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/architecture/agents'
    | '/architecture/deployment'
    | '/architecture/security'
    | '/monitoring/traces'
    | '/opportunities/$id'
    | '/opportunities/new'
    | '/architecture/'
    | '/monitoring/'
    | '/opportunities/'
    | '/api/public/healthz'
    | '/api/public/readyz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  ArchitectureAgentsRoute: typeof ArchitectureAgentsRoute
  ArchitectureDeploymentRoute: typeof ArchitectureDeploymentRoute
  ArchitectureSecurityRoute: typeof ArchitectureSecurityRoute
  MonitoringTracesRoute: typeof MonitoringTracesRoute
  OpportunitiesIdRoute: typeof OpportunitiesIdRoute
  OpportunitiesNewRoute: typeof OpportunitiesNewRoute
  ArchitectureIndexRoute: typeof ArchitectureIndexRoute
  MonitoringIndexRoute: typeof MonitoringIndexRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
  ApiPublicHealthzRoute: typeof ApiPublicHealthzRoute
  ApiPublicReadyzRoute: typeof ApiPublicReadyzRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture/': {
      id: '/architecture/'
      path: '/architecture'
      fullPath: '/architecture/'
      preLoaderRoute: typeof ArchitectureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture/agents': {
      id: '/architecture/agents'
      path: '/architecture/agents'
      fullPath: '/architecture/agents'
      preLoaderRoute: typeof ArchitectureAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture/deployment': {
      id: '/architecture/deployment'
      path: '/architecture/deployment'
      fullPath: '/architecture/deployment'
      preLoaderRoute: typeof ArchitectureDeploymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture/security': {
      id: '/architecture/security'
      path: '/architecture/security'
      fullPath: '/architecture/security'
      preLoaderRoute: typeof ArchitectureSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring/': {
      id: '/monitoring/'
      path: '/monitoring'
      fullPath: '/monitoring/'
      preLoaderRoute: typeof MonitoringIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring/traces': {
      id: '/monitoring/traces'
      path: '/monitoring/traces'
      fullPath: '/monitoring/traces'
      preLoaderRoute: typeof MonitoringTracesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$id': {
      id: '/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/new': {
      id: '/opportunities/new'
      path: '/opportunities/new'
      fullPath: '/opportunities/new'
      preLoaderRoute: typeof OpportunitiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/healthz': {
      id: '/api/public/healthz'
      path: '/api/public/healthz'
      fullPath: '/api/public/healthz'
      preLoaderRoute: typeof ApiPublicHealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/readyz': {
      id: '/api/public/readyz'
      path: '/api/public/readyz'
      fullPath: '/api/public/readyz'
      preLoaderRoute: typeof ApiPublicReadyzRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  ArchitectureAgentsRoute: ArchitectureAgentsRoute,
  ArchitectureDeploymentRoute: ArchitectureDeploymentRoute,
  ArchitectureSecurityRoute: ArchitectureSecurityRoute,
  MonitoringTracesRoute: MonitoringTracesRoute,
  OpportunitiesIdRoute: OpportunitiesIdRoute,
  OpportunitiesNewRoute: OpportunitiesNewRoute,
  ArchitectureIndexRoute: ArchitectureIndexRoute,
  MonitoringIndexRoute: MonitoringIndexRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
  ApiPublicHealthzRoute: ApiPublicHealthzRoute,
  ApiPublicReadyzRoute: ApiPublicReadyzRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
