export const EXPENSE_CATEGORIES = [
  'Food & Dining',
  'Transport',
  'Shopping',
  'Education',
  'Bills & Utilities',
  'Health',
  'Entertainment',
  'Housing',
  'Personal Care',
  'Other',
] as const;

export const INCOME_CATEGORIES = [
  'Salary',
  'Freelance',
  'Allowance',
  'Scholarship',
  'Investment',
  'Other',
] as const;

export const ALL_CATEGORIES = [...EXPENSE_CATEGORIES, ...INCOME_CATEGORIES];

export const CATEGORY_ALIASES: Record<string, string> = {
  food: 'Food & Dining',
  lunch: 'Food & Dining',
  dinner: 'Food & Dining',
  breakfast: 'Food & Dining',
  dining: 'Food & Dining',
  restaurant: 'Food & Dining',
  'food & dining': 'Food & Dining',
  'food and dining': 'Food & Dining',
  transport: 'Transport',
  transportation: 'Transport',
  travel: 'Transport',
  cab: 'Transport',
  fuel: 'Transport',
  shopping: 'Shopping',
  clothes: 'Shopping',
  clothing: 'Shopping',
  education: 'Education',
  tuition: 'Education',
  books: 'Education',
  fees: 'Education',
  'bills & utilities': 'Bills & Utilities',
  'bills and utilities': 'Bills & Utilities',
  bills: 'Bills & Utilities',
  utilities: 'Bills & Utilities',
  electricity: 'Bills & Utilities',
  water: 'Bills & Utilities',
  internet: 'Bills & Utilities',
  phone: 'Bills & Utilities',
  health: 'Health',
  medical: 'Health',
  doctor: 'Health',
  medicine: 'Health',
  entertainment: 'Entertainment',
  movie: 'Entertainment',
  movies: 'Entertainment',
  games: 'Entertainment',
  gaming: 'Entertainment',
  housing: 'Housing',
  rent: 'Housing',
  'personal care': 'Personal Care',
  grooming: 'Personal Care',
  salary: 'Salary',
  freelance: 'Freelance',
  allowance: 'Allowance',
  scholarship: 'Scholarship',
  investment: 'Investment',
  investments: 'Investment',
  other: 'Other',
};
