/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedArchitectureRouteImport } from './routes/_authenticated/architecture'
import { Route as AuthenticatedFocusRouteImport } from './routes/_authenticated/focus'
import { Route as AuthenticatedMonitoringRouteImport } from './routes/_authenticated/monitoring'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated/planner'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedArchitectureDeploymentRouteImport } from './routes/_authenticated/architecture.deployment'
import { Route as AuthenticatedArchitectureSecurityRouteImport } from './routes/_authenticated/architecture.security'
import { Route as AuthenticatedArchitectureWorkflowsRouteImport } from './routes/_authenticated/architecture.workflows'
import { Route as AuthenticatedMonitoringTracesRouteImport } from './routes/_authenticated/monitoring.traces'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArchitectureRoute =
  AuthenticatedArchitectureRouteImport.update({
    id: '/architecture',
    path: '/architecture',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFocusRoute = AuthenticatedFocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonitoringRoute = AuthenticatedMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArchitectureDeploymentRoute =
  AuthenticatedArchitectureDeploymentRouteImport.update({
    id: '/deployment',
    path: '/deployment',
    getParentRoute: () => AuthenticatedArchitectureRoute,
  } as any)
const AuthenticatedArchitectureSecurityRoute =
  AuthenticatedArchitectureSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedArchitectureRoute,
  } as any)
const AuthenticatedArchitectureWorkflowsRoute =
  AuthenticatedArchitectureWorkflowsRouteImport.update({
    id: '/workflows',
    path: '/workflows',
    getParentRoute: () => AuthenticatedArchitectureRoute,
  } as any)
const AuthenticatedMonitoringTracesRoute =
  AuthenticatedMonitoringTracesRouteImport.update({
    id: '/traces',
    path: '/traces',
    getParentRoute: () => AuthenticatedMonitoringRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/architecture': typeof AuthenticatedArchitectureRouteWithChildren
  '/focus': typeof AuthenticatedFocusRoute
  '/monitoring': typeof AuthenticatedMonitoringRouteWithChildren
  '/notes': typeof AuthenticatedNotesRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/architecture/deployment': typeof AuthenticatedArchitectureDeploymentRoute
  '/architecture/security': typeof AuthenticatedArchitectureSecurityRoute
  '/architecture/workflows': typeof AuthenticatedArchitectureWorkflowsRoute
  '/monitoring/traces': typeof AuthenticatedMonitoringTracesRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/architecture': typeof AuthenticatedArchitectureRouteWithChildren
  '/focus': typeof AuthenticatedFocusRoute
  '/monitoring': typeof AuthenticatedMonitoringRouteWithChildren
  '/notes': typeof AuthenticatedNotesRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/': typeof AuthenticatedIndexRoute
  '/architecture/deployment': typeof AuthenticatedArchitectureDeploymentRoute
  '/architecture/security': typeof AuthenticatedArchitectureSecurityRoute
  '/architecture/workflows': typeof AuthenticatedArchitectureWorkflowsRoute
  '/monitoring/traces': typeof AuthenticatedMonitoringTracesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/architecture': typeof AuthenticatedArchitectureRouteWithChildren
  '/_authenticated/focus': typeof AuthenticatedFocusRoute
  '/_authenticated/monitoring': typeof AuthenticatedMonitoringRouteWithChildren
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/architecture/deployment': typeof AuthenticatedArchitectureDeploymentRoute
  '/_authenticated/architecture/security': typeof AuthenticatedArchitectureSecurityRoute
  '/_authenticated/architecture/workflows': typeof AuthenticatedArchitectureWorkflowsRoute
  '/_authenticated/monitoring/traces': typeof AuthenticatedMonitoringTracesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/analytics'
    | '/architecture'
    | '/focus'
    | '/monitoring'
    | '/notes'
    | '/planner'
    | '/profile'
    | '/tasks'
    | '/architecture/deployment'
    | '/architecture/security'
    | '/architecture/workflows'
    | '/monitoring/traces'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/analytics'
    | '/architecture'
    | '/focus'
    | '/monitoring'
    | '/notes'
    | '/planner'
    | '/profile'
    | '/tasks'
    | '/'
    | '/architecture/deployment'
    | '/architecture/security'
    | '/architecture/workflows'
    | '/monitoring/traces'
  id:
    | '__root__'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/analytics'
    | '/_authenticated/architecture'
    | '/_authenticated/focus'
    | '/_authenticated/monitoring'
    | '/_authenticated/notes'
    | '/_authenticated/planner'
    | '/_authenticated/profile'
    | '/_authenticated/tasks'
    | '/_authenticated/'
    | '/_authenticated/architecture/deployment'
    | '/_authenticated/architecture/security'
    | '/_authenticated/architecture/workflows'
    | '/_authenticated/monitoring/traces'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/architecture': {
      id: '/_authenticated/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof AuthenticatedArchitectureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/focus': {
      id: '/_authenticated/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof AuthenticatedFocusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitoring': {
      id: '/_authenticated/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthenticatedMonitoringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/architecture/deployment': {
      id: '/_authenticated/architecture/deployment'
      path: '/deployment'
      fullPath: '/architecture/deployment'
      preLoaderRoute: typeof AuthenticatedArchitectureDeploymentRouteImport
      parentRoute: typeof AuthenticatedArchitectureRoute
    }
    '/_authenticated/architecture/security': {
      id: '/_authenticated/architecture/security'
      path: '/security'
      fullPath: '/architecture/security'
      preLoaderRoute: typeof AuthenticatedArchitectureSecurityRouteImport
      parentRoute: typeof AuthenticatedArchitectureRoute
    }
    '/_authenticated/architecture/workflows': {
      id: '/_authenticated/architecture/workflows'
      path: '/workflows'
      fullPath: '/architecture/workflows'
      preLoaderRoute: typeof AuthenticatedArchitectureWorkflowsRouteImport
      parentRoute: typeof AuthenticatedArchitectureRoute
    }
    '/_authenticated/monitoring/traces': {
      id: '/_authenticated/monitoring/traces'
      path: '/traces'
      fullPath: '/monitoring/traces'
      preLoaderRoute: typeof AuthenticatedMonitoringTracesRouteImport
      parentRoute: typeof AuthenticatedMonitoringRoute
    }
  }
}

interface AuthenticatedArchitectureRouteChildren {
  AuthenticatedArchitectureDeploymentRoute: typeof AuthenticatedArchitectureDeploymentRoute
  AuthenticatedArchitectureSecurityRoute: typeof AuthenticatedArchitectureSecurityRoute
  AuthenticatedArchitectureWorkflowsRoute: typeof AuthenticatedArchitectureWorkflowsRoute
}

const AuthenticatedArchitectureRouteChildren: AuthenticatedArchitectureRouteChildren =
  {
    AuthenticatedArchitectureDeploymentRoute:
      AuthenticatedArchitectureDeploymentRoute,
    AuthenticatedArchitectureSecurityRoute:
      AuthenticatedArchitectureSecurityRoute,
    AuthenticatedArchitectureWorkflowsRoute:
      AuthenticatedArchitectureWorkflowsRoute,
  }

const AuthenticatedArchitectureRouteWithChildren =
  AuthenticatedArchitectureRoute._addFileChildren(
    AuthenticatedArchitectureRouteChildren,
  )

interface AuthenticatedMonitoringRouteChildren {
  AuthenticatedMonitoringTracesRoute: typeof AuthenticatedMonitoringTracesRoute
}

const AuthenticatedMonitoringRouteChildren: AuthenticatedMonitoringRouteChildren =
  {
    AuthenticatedMonitoringTracesRoute: AuthenticatedMonitoringTracesRoute,
  }

const AuthenticatedMonitoringRouteWithChildren =
  AuthenticatedMonitoringRoute._addFileChildren(
    AuthenticatedMonitoringRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedArchitectureRoute: typeof AuthenticatedArchitectureRouteWithChildren
  AuthenticatedFocusRoute: typeof AuthenticatedFocusRoute
  AuthenticatedMonitoringRoute: typeof AuthenticatedMonitoringRouteWithChildren
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedArchitectureRoute: AuthenticatedArchitectureRouteWithChildren,
  AuthenticatedFocusRoute: AuthenticatedFocusRoute,
  AuthenticatedMonitoringRoute: AuthenticatedMonitoringRouteWithChildren,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
