import bcrypt from 'bcryptjs';
import { db } from './db.ts';
import type { IUser, IIssue, INotification } from './models/types.ts';

export async function seedDemoData(): Promise<void> {
  const existingUsersCount = await db.users.countDocuments();
  if (existingUsersCount > 0) {
    // Already seeded or data exists
    return;
  }

  console.log('Seeding initial demo data for CampusFix...');

  const salt = await bcrypt.genSalt(10);
  const adminHashedPassword = await bcrypt.hash('AdminPassword123!', salt);
  const studentHashedPassword = await bcrypt.hash('StudentPass123!', salt);

  const adminUser: Omit<IUser, '_id'> & { _id: string } = {
    _id: 'user_admin_001',
    name: 'Campus Facility Administrator',
    email: 'admin@campusfix.edu',
    password: adminHashedPassword,
    department: 'Estate & Campus Facilities Directorate',
    year: 'Faculty/Admin',
    role: 'admin',
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  };

  const studentAlex: Omit<IUser, '_id'> & { _id: string } = {
    _id: 'user_student_001',
    name: 'Alex Chen',
    email: 'alex.chen@campusfix.edu',
    password: studentHashedPassword,
    department: 'Computer Science & Engineering',
    year: '3rd Year',
    role: 'student',
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
  };

  const studentPriya: Omit<IUser, '_id'> & { _id: string } = {
    _id: 'user_student_002',
    name: 'Priya Patel',
    email: 'priya.patel@campusfix.edu',
    password: studentHashedPassword,
    department: 'Mechanical Engineering',
    year: '2nd Year',
    role: 'student',
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
  };

  await db.users.insertMany([adminUser, studentAlex, studentPriya]);

  const sampleIssues: Array<Omit<IIssue, '_id'> & { _id: string }> = [
    {
      _id: 'issue_cf_1001',
      issueId: 'CF-2026-1001',
      studentId: studentAlex._id,
      studentName: studentAlex.name,
      studentEmail: studentAlex.email,
      studentDepartment: studentAlex.department,
      title: 'Water leaking continuously in hostel 4th floor bathroom',
      description: 'The overhead pipe joint in the 4th floor west wing washroom has cracked. Water is pooling rapidly across the floor creating a slipping hazard.',
      category: 'Hostel',
      location: 'Hostel Block B, 4th Floor, West Wing Restroom',
      priority: 'High',
      status: 'In Progress',
      assignedDepartment: 'Plumbing & Civil Maintenance',
      adminRemarks: 'Maintenance team dispatched. Main valve temporarily shut; pipe replacement in progress.',
      imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80',
      statusHistory: [
        {
          status: 'Pending',
          changedBy: studentAlex.name,
          changedByRole: 'student',
          timestamp: new Date(Date.now() - 2 * 86400000).toISOString(),
          remarks: 'Issue reported by student.',
        },
        {
          status: 'Assigned',
          changedBy: 'Campus Facility Administrator',
          changedByRole: 'admin',
          timestamp: new Date(Date.now() - 1.8 * 86400000).toISOString(),
          department: 'Plumbing & Civil Maintenance',
          remarks: 'Assigned to Mr. Robert (Plumbing Supervisor).',
        },
        {
          status: 'In Progress',
          changedBy: 'Campus Facility Administrator',
          changedByRole: 'admin',
          timestamp: new Date(Date.now() - 1 * 86400000).toISOString(),
          remarks: 'Technicians on site repairing the pipe fitting.',
        },
      ],
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      _id: 'issue_cf_1002',
      issueId: 'CF-2026-1002',
      studentId: studentAlex._id,
      studentName: studentAlex.name,
      studentEmail: studentAlex.email,
      studentDepartment: studentAlex.department,
      title: 'Ceiling projector lamp blown in Lecture Hall 302',
      description: 'The overhead EPSON projector turned off with a loud pop and blinking red warning indicator during Advanced Algorithms class.',
      category: 'Classroom',
      location: 'Academic Complex Block 2, Lecture Hall 302',
      priority: 'Medium',
      status: 'Resolved',
      assignedDepartment: 'Academic Facilities & Audio-Visual Cell',
      adminRemarks: 'Replaced optical bulb assembly and tested HDMI signal transmission. Working normally.',
      statusHistory: [
        {
          status: 'Pending',
          changedBy: studentAlex.name,
          changedByRole: 'student',
          timestamp: new Date(Date.now() - 5 * 86400000).toISOString(),
        },
        {
          status: 'Assigned',
          changedBy: 'Campus Facility Administrator',
          changedByRole: 'admin',
          timestamp: new Date(Date.now() - 4.5 * 86400000).toISOString(),
          department: 'Academic Facilities & Audio-Visual Cell',
        },
        {
          status: 'In Progress',
          changedBy: 'Campus Facility Administrator',
          changedByRole: 'admin',
          timestamp: new Date(Date.now() - 4 * 86400000).toISOString(),
        },
        {
          status: 'Resolved',
          changedBy: 'Campus Facility Administrator',
          changedByRole: 'admin',
          timestamp: new Date(Date.now() - 3.8 * 86400000).toISOString(),
          remarks: 'Bulb replaced and color calibration verified.',
        },
      ],
      createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 3.8 * 86400000).toISOString(),
    },
    {
      _id: 'issue_cf_1003',
      issueId: 'CF-2026-1003',
      studentId: studentPriya._id,
      studentName: studentPriya.name,
      studentEmail: studentPriya.email,
      studentDepartment: studentPriya.department,
      title: 'CNC milling machine safety emergency stop switch stuck',
      description: 'The red emergency cut-off button on CNC Mill #3 remains depressed and cannot be reset mechanically. Machine is offline.',
      category: 'Laboratory',
      location: 'Mechanical Workshop, Advanced Machining Lab B-04',
      priority: 'Critical',
      status: 'Assigned',
      assignedDepartment: 'Laboratory Technical Support & Safety Cell',
      adminRemarks: 'Machine locked out with LOTO tag. Vendor technician scheduled for inspection today.',
      statusHistory: [
        {
          status: 'Pending',
          changedBy: studentPriya.name,
          changedByRole: 'student',
          timestamp: new Date(Date.now() - 1 * 86400000).toISOString(),
        },
        {
          status: 'Assigned',
          changedBy: 'Campus Facility Administrator',
          changedByRole: 'admin',
          timestamp: new Date(Date.now() - 0.8 * 86400000).toISOString(),
          department: 'Laboratory Technical Support & Safety Cell',
          remarks: 'Safety officer alerted. Machine isolated.',
        },
      ],
      createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 0.8 * 86400000).toISOString(),
    },
    {
      _id: 'issue_cf_1004',
      issueId: 'CF-2026-1004',
      studentId: studentAlex._id,
      studentName: studentAlex.name,
      studentEmail: studentAlex.email,
      studentDepartment: studentAlex.department,
      title: 'High latency and frequent packet loss on Central Library Wi-Fi',
      description: 'Connecting to "Campus_Secure_5G" in 2nd floor reading room drops connection every 3 minutes. Speedtest shows 0.2 Mbps down.',
      category: 'Internet',
      location: 'Central Library, 2nd Floor Silent Study Wing',
      priority: 'Medium',
      status: 'Pending',
      assignedDepartment: 'Network & IT Infrastructure Cell',
      adminRemarks: '',
      statusHistory: [
        {
          status: 'Pending',
          changedBy: studentAlex.name,
          changedByRole: 'student',
          timestamp: new Date(Date.now() - 0.5 * 86400000).toISOString(),
          remarks: 'Issue registered by student.',
        },
      ],
      createdAt: new Date(Date.now() - 0.5 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 0.5 * 86400000).toISOString(),
    },
    {
      _id: 'issue_cf_1005',
      issueId: 'CF-2026-1005',
      studentId: studentPriya._id,
      studentName: studentPriya.name,
      studentEmail: studentPriya.email,
      studentDepartment: studentPriya.department,
      title: 'Broken electrical switchboard with exposed wires near stairwell',
      description: 'Plastic faceplate broken off in building stairwell. Live copper terminals are exposed at chest height.',
      category: 'Electricity',
      location: 'Science Block, West Stairwell between 1st & 2nd floors',
      priority: 'Critical',
      status: 'In Progress',
      assignedDepartment: 'Electrical Works & Power Division',
      adminRemarks: 'Area cordoned off. Power circuit isolated at main DB. Replacement modular faceplate being installed.',
      statusHistory: [
        {
          status: 'Pending',
          changedBy: studentPriya.name,
          changedByRole: 'student',
          timestamp: new Date(Date.now() - 1.5 * 86400000).toISOString(),
        },
        {
          status: 'Assigned',
          changedBy: 'Campus Facility Administrator',
          changedByRole: 'admin',
          timestamp: new Date(Date.now() - 1.3 * 86400000).toISOString(),
          department: 'Electrical Works & Power Division',
        },
        {
          status: 'In Progress',
          changedBy: 'Campus Facility Administrator',
          changedByRole: 'admin',
          timestamp: new Date(Date.now() - 0.9 * 86400000).toISOString(),
          remarks: 'Electrician on site with replacement materials.',
        },
      ],
      createdAt: new Date(Date.now() - 1.5 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 0.9 * 86400000).toISOString(),
    },
    {
      _id: 'issue_cf_1006',
      issueId: 'CF-2026-1006',
      studentId: studentAlex._id,
      studentName: studentAlex.name,
      studentEmail: studentAlex.email,
      studentDepartment: studentAlex.department,
      title: 'Overflowing recycle bins near cafeteria entrance',
      description: 'Recycling and compost bins have exceeded capacity since yesterday afternoon; plastic cups and containers are spilling onto the walkway.',
      category: 'Cleanliness',
      location: 'Student Activity Center, South Plaza Cafeteria entrance',
      priority: 'Low',
      status: 'Resolved',
      assignedDepartment: 'Sanitation & Housekeeping Division',
      adminRemarks: 'Bins emptied and sanitized. Housekeeping schedule updated for extra afternoon sweep.',
      statusHistory: [
        {
          status: 'Pending',
          changedBy: studentAlex.name,
          changedByRole: 'student',
          timestamp: new Date(Date.now() - 6 * 86400000).toISOString(),
        },
        {
          status: 'Assigned',
          changedBy: 'Campus Facility Administrator',
          changedByRole: 'admin',
          timestamp: new Date(Date.now() - 5.8 * 86400000).toISOString(),
          department: 'Sanitation & Housekeeping Division',
        },
        {
          status: 'Resolved',
          changedBy: 'Campus Facility Administrator',
          changedByRole: 'admin',
          timestamp: new Date(Date.now() - 5.5 * 86400000).toISOString(),
          remarks: 'Cleaned and cleared.',
        },
      ],
      createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 5.5 * 86400000).toISOString(),
    },
    {
      _id: 'issue_cf_1007',
      issueId: 'CF-2026-1007',
      studentId: studentPriya._id,
      studentName: studentPriya.name,
      studentEmail: studentPriya.email,
      studentDepartment: studentPriya.department,
      title: 'Water cooler dispensing warm water and making humming noise',
      description: 'The stainless steel drinking fountain on floor 2 is not chilling water and makes a loud vibrating noise when pressed.',
      category: 'Water',
      location: 'Engineering Tower B, 2nd Floor Corridor',
      priority: 'Medium',
      status: 'Pending',
      assignedDepartment: 'Plumbing & Civil Maintenance',
      adminRemarks: '',
      statusHistory: [
        {
          status: 'Pending',
          changedBy: studentPriya.name,
          changedByRole: 'student',
          timestamp: new Date(Date.now() - 0.2 * 86400000).toISOString(),
        },
      ],
      createdAt: new Date(Date.now() - 0.2 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 0.2 * 86400000).toISOString(),
    },
    {
      _id: 'issue_cf_1008',
      issueId: 'CF-2026-1008',
      studentId: studentAlex._id,
      studentName: studentAlex.name,
      studentEmail: studentAlex.email,
      studentDepartment: studentAlex.department,
      title: 'Evening shuttle bus Route 4 delayed over 45 minutes consistently',
      description: 'The 6:00 PM campus shuttle towards North Metro has consistently arrived after 6:45 PM all week with no driver dispatch update.',
      category: 'Transport',
      location: 'Main Gate Campus Transit Stop #2',
      priority: 'Medium',
      status: 'Assigned',
      assignedDepartment: 'Campus Transport Fleet Operations',
      adminRemarks: 'Coordinating with fleet manager regarding route roadworks detour.',
      statusHistory: [
        {
          status: 'Pending',
          changedBy: studentAlex.name,
          changedByRole: 'student',
          timestamp: new Date(Date.now() - 2.5 * 86400000).toISOString(),
        },
        {
          status: 'Assigned',
          changedBy: 'Campus Facility Administrator',
          changedByRole: 'admin',
          timestamp: new Date(Date.now() - 2.2 * 86400000).toISOString(),
          department: 'Campus Transport Fleet Operations',
        },
      ],
      createdAt: new Date(Date.now() - 2.5 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 2.2 * 86400000).toISOString(),
    },
    {
      _id: 'issue_cf_1009',
      issueId: 'CF-2026-1009',
      studentId: studentPriya._id,
      studentName: studentPriya.name,
      studentEmail: studentPriya.email,
      studentDepartment: studentPriya.department,
      title: 'Air conditioning unit blowing warm air in East Study Hall',
      description: 'East Study Hall temperature reached 29°C today. The thermostat displays error code E4 and condenser unit outside is silent.',
      category: 'Library',
      location: 'Central Library, East Study Hall, Room 104',
      priority: 'High',
      status: 'In Progress',
      assignedDepartment: 'Electrical Works & Power Division',
      adminRemarks: 'HVAC technician diagnosed low refrigerant; pressure test currently being conducted.',
      statusHistory: [
        {
          status: 'Pending',
          changedBy: studentPriya.name,
          changedByRole: 'student',
          timestamp: new Date(Date.now() - 3 * 86400000).toISOString(),
        },
        {
          status: 'Assigned',
          changedBy: 'Campus Facility Administrator',
          changedByRole: 'admin',
          timestamp: new Date(Date.now() - 2.8 * 86400000).toISOString(),
          department: 'Electrical Works & Power Division',
        },
        {
          status: 'In Progress',
          changedBy: 'Campus Facility Administrator',
          changedByRole: 'admin',
          timestamp: new Date(Date.now() - 2 * 86400000).toISOString(),
          remarks: 'HVAC team working on the rooftop condenser unit.',
        },
      ],
      createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      _id: 'issue_cf_1010',
      issueId: 'CF-2026-1010',
      studentId: studentAlex._id,
      studentName: studentAlex.name,
      studentEmail: studentAlex.email,
      studentDepartment: studentAlex.department,
      title: 'Unsanitary tray return conveyor belt in Food Court',
      description: 'Food residue has accumulated along the automatic roller belt at station 2, causing bad odors and attracting flies.',
      category: 'Canteen',
      location: 'Main Dining Commons, First Floor Dish Return Station #2',
      priority: 'High',
      status: 'Resolved',
      assignedDepartment: 'Campus Hospitality & Food Safety Committee',
      adminRemarks: 'Deep steam cleaned and food-grade disinfectant applied. Conveyor mechanism serviced.',
      statusHistory: [
        {
          status: 'Pending',
          changedBy: studentAlex.name,
          changedByRole: 'student',
          timestamp: new Date(Date.now() - 4 * 86400000).toISOString(),
        },
        {
          status: 'Assigned',
          changedBy: 'Campus Facility Administrator',
          changedByRole: 'admin',
          timestamp: new Date(Date.now() - 3.8 * 86400000).toISOString(),
          department: 'Campus Hospitality & Food Safety Committee',
        },
        {
          status: 'Resolved',
          changedBy: 'Campus Facility Administrator',
          changedByRole: 'admin',
          timestamp: new Date(Date.now() - 3.2 * 86400000).toISOString(),
          remarks: 'Steam sanitation completed and inspected by food hygiene officer.',
        },
      ],
      createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 3.2 * 86400000).toISOString(),
    },
  ];

  await db.issues.insertMany(sampleIssues);

  // Sample Notifications for students
  const sampleNotifications: Array<Omit<INotification, '_id'> & { _id: string }> = [
    {
      _id: 'notif_1',
      userId: studentAlex._id,
      message: 'Your issue CF-2026-1001 (Water leaking) is now In Progress by Plumbing & Civil Maintenance.',
      type: 'status_change',
      issueId: 'CF-2026-1001',
      read: false,
      createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      _id: 'notif_2',
      userId: studentAlex._id,
      message: 'Your issue CF-2026-1002 (Lecture Hall 302 projector) has been Resolved!',
      type: 'resolved',
      issueId: 'CF-2026-1002',
      read: true,
      createdAt: new Date(Date.now() - 3.8 * 86400000).toISOString(),
    },
    {
      _id: 'notif_3',
      userId: studentPriya._id,
      message: 'Your issue CF-2026-1003 has been Assigned to Laboratory Technical Support & Safety Cell.',
      type: 'assigned',
      issueId: 'CF-2026-1003',
      read: false,
      createdAt: new Date(Date.now() - 0.8 * 86400000).toISOString(),
    },
    {
      _id: 'notif_4',
      userId: studentPriya._id,
      message: 'Admin added remark to CF-2026-1005: "Power circuit isolated; replacement faceplate being installed."',
      type: 'remark',
      issueId: 'CF-2026-1005',
      read: false,
      createdAt: new Date(Date.now() - 0.9 * 86400000).toISOString(),
    },
  ];

  await db.notifications.insertMany(sampleNotifications);

  console.log('Demo seed data populated successfully: 1 Admin, 2 Students, 10 Issues, 4 Notifications.');
}
