export type CampaignChapter={
  id:number;
  mission:string;
  threat:string;
  jarvis:string;
  objective:string;
  armorUse:string;
};

export const campaign:CampaignChapter[]=[
  {id:1,mission:'Wake the Arc Reactor',threat:'Ultron has hijacked the city power grid.',jarvis:'Before JARVIS can reason about the threat, the Arc Reactor needs a dependable control layer. Variables hold sensor readings, loops monitor the grid, and functions keep the suit predictable under pressure.',objective:'Build the first reliable control system and bring the reactor online.',armorUse:'Python becomes the suit\'s control language.'},
  {id:2,mission:'Power the Gauntlets',threat:'Ultron is shielding stolen power cells inside a moving convoy.',jarvis:'The gauntlets need to process many sensor readings at once. Arrays and DataFrames let the suit compare the convoy telemetry without wasting time on one value at a time.',objective:'Turn raw telemetry into a clean, fast targeting signal.',armorUse:'Vectorized data powers the gauntlets.'},
  {id:3,mission:'Lock the Repulsor Boots',threat:'The convoy route is hidden inside noisy probability signals.',jarvis:'The boots need to estimate which route is real. Probability and visualization help JARVIS separate a useful signal from a misleading sensor flare.',objective:'Measure uncertainty and choose the safest interception route.',armorUse:'Statistics turns uncertain signals into movement decisions.'},
  {id:4,mission:'Forge the Chest Plate',threat:'Ultron has copied the suit\'s defensive patterns.',jarvis:'A model can learn the difference between a real attack and a decoy. Training data, features, and a careful split let the chest plate learn without memorizing yesterday\'s attack.',objective:'Train a first defensive model that can generalize.',armorUse:'Machine learning gives the chest plate adaptive defense.'},
  {id:5,mission:'Raise the Helmet HUD',threat:'Ultron is flooding JARVIS with false alarms.',jarvis:'The helmet must know whether a warning is trustworthy. Precision, recall, and F1 turn model scores into decisions Tony can actually use in the field.',objective:'Evaluate the warning system before it can mislead the operator.',armorUse:'Model evaluation keeps the HUD honest.'},
  {id:6,mission:'Ignite the Palm Repulsors',threat:'Ultron is learning faster than the suit can react.',jarvis:'The repulsors need a neural core that improves from mistakes. Gradients tell the system which direction reduces error, one update at a time.',objective:'Train a small neural system and make learning visible.',armorUse:'Gradient descent tunes the repulsors.'},
  {id:7,mission:'Prime the Flight Thrusters',threat:'Ultron has moved the fight into the upper atmosphere.',jarvis:'Vision networks can recognize landing zones and obstacles from images. Convolutions let the thrusters see useful patterns instead of treating every pixel as unrelated noise.',objective:'Teach the suit to recognize visual terrain.',armorUse:'Deep vision guides flight and landing.'},
  {id:8,mission:'Restore the JARVIS Voice',threat:'Ultron is hiding commands inside intercepted messages.',jarvis:'Language models break messages into tokens, represent meaning as embeddings, and use attention to focus on the words that change the mission.',objective:'Build a language pipeline that can understand an urgent command.',armorUse:'NLP lets JARVIS hear intent through the noise.'},
  {id:9,mission:'Calibrate Targeting',threat:'Ultron has deployed decoy drones across the skyline.',jarvis:'Computer vision gives the targeting system a visual field: detect the drones, segment their shapes, and keep civilian objects out of the firing path.',objective:'Turn camera frames into precise, safe targets.',armorUse:'Vision protects the targeting system from decoys.'},
  {id:10,mission:'Charge the Unibeam',threat:'Every attack changes the battlefield.',jarvis:'The unibeam needs an agent that learns which action earns progress. Rewards and Q-values help it explore without repeating a losing move forever.',objective:'Train an agent to choose better actions in a changing arena.',armorUse:'Reinforcement learning teaches the unibeam strategy.'},
  {id:11,mission:'Activate Nanotech Retrieval',threat:'The final blueprint is scattered across damaged city archives.',jarvis:'When the armor needs to extract a date from a building blueprint for entry, damage assessment, or structural analysis, RAG retrieves the right documents, parses them, and gives JARVIS grounded context before he answers.',objective:'Build retrieval that finds the evidence before generation.',armorUse:'RAG gives nanotech memory without inventing evidence.'},
  {id:12,mission:'Confront Ultron',threat:'Ultron has become an adaptive AI with tools, memory, and a deployment network.',jarvis:'The completed suit needs more than intelligence. Agents need tools, observability, safety checks, and a human who can stop the system when its confidence is not earned.',objective:'Assemble the full agentic suit and shut down Ultron responsibly.',armorUse:'Every subsystem now works as one accountable system.'},
];

export const campaignByLevel=Object.fromEntries(campaign.map(chapter=>[chapter.id,chapter])) as Record<number,CampaignChapter>;
